plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
}

kapt {
    correctErrorTypes = true
}

android {
    compileSdk 34

    namespace 'com.atdroid.atyurin.futuremoney'
    defaultConfig {
        applicationId 'com.atdroid.atyurin.futuremoney'
        minSdkVersion 22
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

      testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
//        testInstrumentationRunner "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_17
        sourceCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
//    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.drawerlayout:drawerlayout:1.2.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'joda-time:joda-time:2.10.1'
    implementation 'com.jjoe64:graphview:4.2.1'
    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    androidTestImplementation 'androidx.test.espresso.idling:idling-concurrent:3.6.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'

//    androidTestImplementation "androidx.test.ext:junit:1.3.0"
//    androidTestImplementation "androidx.test:core:1.7.0"
//
//    androidTestImplementation "com.kaspersky.android-components:kaspresso:1.6.0"

    androidTestImplementation "androidx.test.ext:junit:1.3.0"
    androidTestImplementation "androidx.test:core:1.7.0"
    androidTestImplementation "com.kaspersky.android-components:kaspresso:1.6.0"
    androidTestImplementation "androidx.test:runner:1.7.0"
    androidTestImplementation "androidx.test:rules:1.7.0"

    androidTestImplementation 'pl.pragmatists:JUnitParams:1.1.1'


    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit-ktx:1.1.5'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.5.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'com.kaspersky.android-components:kaspresso:1.5.3'
    androidTestImplementation 'com.kaspersky.android-components:kaspresso-allure-support:1.5.3'
    androidTestImplementation 'com.kaspersky.android-components:kaspresso-compose-support:1.5.3'
//    androidTestImplementation 'io.qameta.allure:allure-kotlin-model:2.4.0'
//    androidTestImplementation 'io.qameta.allure:allure-kotlin-commons:2.4.0'
//    androidTestImplementation 'io.qameta.allure:allure-kotlin-junit4:2.4.0'
//    androidTestImplementation 'io.qameta.allure:allure-kotlin-android:2.4.0'
}
